// Embedded injury diagnosis library v1.1 - static config
export const injuryDiagnosisLibraryV1_1 = {
  "config_name": "injury_diagnosis_library",
  "version": "1.1",
  "global": {
    "confirm_status": { "key": "confirmed", "label": "Confirmed status", "type": "enum", "options": ["suspected", "confirmed"], "default": "suspected" },
    "severity_generic": { "key": "severity", "label": "Severity", "type": "enum", "options": ["irritation", "sprain", "partial_tear", "full_thickness_tear", "rupture"], "optional": true },
    "muscle_grading": { "key": "muscle_grade", "label": "Muscle grading", "type": "object", "optional": true, "fields": [{ "key": "system", "label": "Classification system", "type": "enum", "options": ["BAMIC", "PEDRET_US"] }, { "key": "grade", "label": "Grade", "type": "string", "hint": "Store as string to support different grading formats (e.g., 1a, 2b, etc.)" }, { "key": "mechanism", "label": "Mechanism", "type": "enum", "options": ["running", "stretching"], "optional": true }] },
    "laterality": { "key": "side", "label": "Side", "type": "enum", "options": ["left", "right", "bilateral", "midline"], "default": "left" },
    "spine_level": { "key": "level", "label": "Level", "type": "string", "optional": true, "hint": "e.g., L4/5, L5/S1, C5/6" },
    "disc_details": { "key": "disc_details", "label": "Disc details", "type": "object", "optional": true, "fields": [{ "key": "morphology", "label": "Morphology", "type": "enum", "options": ["bulge", "protrusion", "extrusion", "sequestration"] }, { "key": "location", "label": "Location", "type": "enum", "options": ["central", "paracentral", "foraminal", "extraforaminal"], "optional": true }, { "key": "level", "label": "Level", "type": "string", "optional": true }] },
    "oa_compartment_knee": { "key": "oa_compartment", "label": "OA compartment", "type": "enum", "options": ["pfj", "medial", "lateral", "tricompartmental"], "optional": true },
    "hip_impingement_type": { "key": "impingement_type", "label": "FAI type", "type": "enum", "options": ["cam", "pincer", "mixed"], "optional": true },
    "meniscus_details": { "key": "meniscus_details", "label": "Meniscus tear details", "type": "object", "optional": true, "fields": [{ "key": "side", "label": "Meniscus side", "type": "enum", "options": ["medial", "lateral"] }, { "key": "location", "label": "Location", "type": "enum", "options": ["anterior_horn", "body", "posterior_horn", "root"], "optional": true }, { "key": "zone", "label": "Zone", "type": "enum", "options": ["red_red", "red_white", "white_white"], "optional": true }, { "key": "tear_type", "label": "Tear morphology", "type": "enum", "options": ["radial", "longitudinal_vertical", "horizontal", "oblique_parrot_beak", "complex", "degenerative"] }, { "key": "bucket_handle", "label": "Bucket-handle", "type": "boolean", "optional": true }, { "key": "displaced", "label": "Displaced fragment", "type": "boolean", "optional": true }, { "key": "parameniscal_cyst", "label": "Parameniscal cyst", "type": "boolean", "optional": true }] }
  },
  "picklists": {
    "foot_joints": ["tibiotalar_ankle", "subtalar", "talonavicular", "calcaneocuboid", "naviculocuneiform", "tarsometatarsal_1", "tarsometatarsal_2", "tarsometatarsal_3", "tarsometatarsal_4", "tarsometatarsatarsal_5", "mtp_1", "mtp_2", "mtp_3", "mtp_4", "mtp_5", "hallux_ip", "toe_pip", "toe_dip"],
    "wrist_hand_bones_joints": ["distal_radius", "distal_ulna", "druj", "radiocarpal", "scaphoid", "lunate", "triquetrum", "pisiform", "trapezium", "trapezoid", "capitate", "hamate", "metacarpal_1", "metacarpal_2", "metacarpal_3", "metacarpal_4", "metacarpal_5", "phalanx_proximal", "phalanx_middle", "phalanx_distal", "cmc", "mcp", "pip", "dip"]
  },
  "regions": [
    { "region_key": "foot_ankle", "label": "Foot & Ankle", "default_sides": ["left", "right"], "groups": [{ "group_key": "ligaments", "label": "Ligaments", "items": [{ "issue_key": "atfl_injury", "label": "ATFL", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "cfl_injury", "label": "CFL", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "deltoid_complex_injury", "label": "Deltoid complex", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "syndesmosis_aitfl_injury", "label": "Syndesmosis / AITFL", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "tendons_fascia", "label": "Tendons / Fascia", "items": [{ "issue_key": "achilles_tendon_issue", "label": "Achilles tendon (tendinopathy/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "achilles_paratenonitis", "label": "Achilles paratenonitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "plantar_fascia_issue", "label": "Plantar fascia (fasciopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "tib_post_issue", "label": "Tibialis posterior (dysfunction/synovitis/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "peroneal_tendon_issue", "label": "Peroneal tendinopathy/synovitis/tear", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "joint_bone_other", "label": "Joint / Bone / Other", "items": [{ "issue_key": "ankle_joint_issue", "label": "Ankle joint (effusion/synovitis/OA)", "modifiers": ["global.confirm_status"] }, { "issue_key": "subtalar_oa", "label": "Subtalar OA", "modifiers": ["global.confirm_status"] }, { "issue_key": "foot_oa_named_joint", "label": "Foot OA (named joint)", "modifiers": ["global.confirm_status"] }, { "issue_key": "olt_talus", "label": "Osteochondral lesion of talus (OLT/OCD)", "modifiers": ["global.confirm_status"] }, { "issue_key": "lisfranc_injury", "label": "Lisfranc injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "stress_fracture_foot_ankle", "label": "Stress fracture (foot/ankle)", "modifiers": ["global.confirm_status"] }] }, { "group_key": "nerve", "label": "Nerve", "items": [{ "issue_key": "mortons_neuroma", "label": "Morton's neuroma", "modifiers": ["global.confirm_status"] }, { "issue_key": "tarsal_tunnel", "label": "Tarsal tunnel syndrome", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "lower_leg", "label": "Lower leg", "default_sides": ["left", "right"], "groups": [{ "group_key": "muscle", "label": "Muscle", "items": [{ "issue_key": "calf_strain_tear", "label": "Calf strain/tear (gastroc/soleus)", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "plantaris_strain_tear", "label": "Plantaris strain/tear", "modifiers": ["global.confirm_status", "global.muscle_grading"] }] }, { "group_key": "tendon", "label": "Tendon", "items": [{ "issue_key": "achilles_tendon_issue", "label": "Achilles tendon (tendinopathy/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "bone", "label": "Bone", "items": [{ "issue_key": "mtss_shin_splints", "label": "Medial tibial stress syndrome (shin splints)", "modifiers": ["global.confirm_status"] }, { "issue_key": "tibial_stress_fracture", "label": "Tibial stress fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "fibular_stress_fracture", "label": "Fibular stress fracture", "modifiers": ["global.confirm_status"] }] }, { "group_key": "other", "label": "Other", "items": [{ "issue_key": "cecs_lower_leg", "label": "Chronic exertional compartment syndrome", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "knee", "label": "Knee", "default_sides": ["left", "right"], "groups": [{ "group_key": "tendon", "label": "Tendon", "items": [{ "issue_key": "patellar_tendon_issue", "label": "Patellar tendon (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "quad_tendon_issue", "label": "Quadriceps tendon (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "pes_anserine_bursa_tendon", "label": "Pes anserine tendinopathy/bursitis", "modifiers": ["global.confirm_status"] }] }, { "group_key": "ligament", "label": "Ligament", "items": [{ "issue_key": "acl_injury", "label": "ACL (sprain/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "pcl_injury", "label": "PCL (sprain/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "mcl_injury", "label": "MCL (sprain/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "lcl_injury", "label": "LCL (sprain/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "mpfl_injury", "label": "MPFL injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "plc_injury", "label": "Posterolateral corner (PLC) injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "meniscus", "label": "Meniscus", "items": [{ "issue_key": "medial_meniscus_tear", "label": "Medial meniscus tear", "modifiers": ["global.confirm_status", "global.meniscus_details"] }, { "issue_key": "lateral_meniscus_tear", "label": "Lateral meniscus tear", "modifiers": ["global.confirm_status", "global.meniscus_details"] }, { "issue_key": "meniscus_root_tear", "label": "Meniscus root tear", "modifiers": ["global.confirm_status", "global.meniscus_details"] }] }, { "group_key": "joint", "label": "Joint / OA / Cartilage", "items": [{ "issue_key": "knee_oa", "label": "Knee osteoarthritis", "modifiers": ["global.confirm_status", "global.oa_compartment_knee"] }, { "issue_key": "chondral_defect", "label": "Chondral defect / chondromalacia", "modifiers": ["global.confirm_status"] }, { "issue_key": "synovitis_effusion", "label": "Synovitis / effusion", "modifiers": ["global.confirm_status"] }] }, { "group_key": "other", "label": "Other", "items": [{ "issue_key": "itb_friction", "label": "ITB friction syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "bakers_cyst", "label": "Baker's cyst", "modifiers": ["global.confirm_status"] }, { "issue_key": "pfps", "label": "Patellofemoral pain syndrome", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "anterior_thigh", "label": "Anterior thigh", "default_sides": ["left", "right"], "groups": [{ "group_key": "muscle", "label": "Muscle", "items": [{ "issue_key": "quadriceps_strain_tear", "label": "Quadriceps strain/tear", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "hip_flexor_strain", "label": "Hip flexor strain (iliopsoas/rectus femoris)", "modifiers": ["global.confirm_status", "global.muscle_grading"] }] }] },
    { "region_key": "posterior_thigh", "label": "Posterior thigh", "default_sides": ["left", "right"], "groups": [{ "group_key": "muscle_tendon", "label": "Muscle / Tendon", "items": [{ "issue_key": "hamstring_strain_tear", "label": "Hamstring strain/tear", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "prox_hamstring_tendinopathy", "label": "Proximal hamstring tendinopathy", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "hip_groin", "label": "Hip / Groin", "default_sides": ["left", "right"], "groups": [{ "group_key": "joint_labrum_fai", "label": "Joint / Labrum / FAI", "items": [{ "issue_key": "labral_tear", "label": "Labral tear", "modifiers": ["global.confirm_status"] }, { "issue_key": "fai_confirmed", "label": "Femoroacetabular impingement (confirmed)", "modifiers": ["global.confirm_status", "global.hip_impingement_type"] }, { "issue_key": "hip_oa", "label": "Hip osteoarthritis", "modifiers": ["global.confirm_status"] }, { "issue_key": "avn", "label": "AVN", "modifiers": ["global.confirm_status"] }, { "issue_key": "scfe", "label": "SCFE", "modifiers": ["global.confirm_status"] }] }, { "group_key": "tendon_bursa", "label": "Tendon / Bursa", "items": [{ "issue_key": "gtps", "label": "GTPS", "modifiers": ["global.confirm_status"] }, { "issue_key": "gluteal_tear", "label": "Gluteus medius/minimus tear", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "iliopsoas_tendinopathy", "label": "Iliopsoas tendinopathy / snapping hip", "modifiers": ["global.confirm_status"] }] }, { "group_key": "groin_pubis", "label": "Groin / Pubis", "items": [{ "issue_key": "sports_hernia", "label": "Sports hernia / inguinal disruption", "modifiers": ["global.confirm_status"] }, { "issue_key": "osteitis_pubis", "label": "Osteitis pubis", "modifiers": ["global.confirm_status"] }, { "issue_key": "adductor_related_groin_pain", "label": "Adductor-related groin pain", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "hernia", "label": "Hernia", "modifiers": ["global.confirm_status"] }] }, { "group_key": "bone_stress", "label": "Bone / Stress", "items": [{ "issue_key": "femoral_neck_stress_fracture", "label": "Femoral neck stress fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "pelvic_stress_fracture", "label": "Pelvic stress fracture", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "lumbar_sacrum", "label": "Lumbar spine / Sacrum", "default_sides": ["midline", "left", "right", "bilateral"], "groups": [{ "group_key": "spine", "label": "Spine diagnoses", "items": [{ "issue_key": "nsmlbp", "label": "Non-specific mechanical low back pain", "modifiers": ["global.confirm_status"] }, { "issue_key": "facet_arthropathy_lumbar", "label": "Facet joint syndrome/arthropathy", "modifiers": ["global.confirm_status"] }, { "issue_key": "lumbar_radiculopathy", "label": "Lumbar radiculopathy", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "central_canal_stenosis_lumbar", "label": "Central canal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "foraminal_stenosis_lumbar", "label": "Foraminal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "discogenic_lumbar", "label": "Discogenic pain", "modifiers": ["global.confirm_status", "global.disc_details"] }, { "issue_key": "annular_fissure", "label": "Annular fissure/tear", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "cauda_equina", "label": "Cauda equina syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolisthesis_lumbar", "label": "Spondylolisthesis", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolysis_lumbar", "label": "Spondylolysis", "modifiers": ["global.confirm_status"] }, { "issue_key": "fracture_lumbar", "label": "Fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "si_joint_dysfunction", "label": "SI joint dysfunction", "modifiers": ["global.confirm_status"] }, { "issue_key": "sacroiliitis", "label": "Sacroiliitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "ankylosing_spondylitis", "label": "Ankylosing spondylitis", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "thoracic_spine", "label": "Thoracic spine", "default_sides": ["midline", "left", "right", "bilateral"], "groups": [{ "group_key": "spine", "label": "Spine diagnoses", "items": [{ "issue_key": "facet_arthropathy_thoracic", "label": "Facet joint syndrome/arthropathy", "modifiers": ["global.confirm_status"] }, { "issue_key": "thoracic_radiculopathy", "label": "Thoracic radiculopathy", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "central_canal_stenosis_thoracic", "label": "Central canal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "foraminal_stenosis_thoracic", "label": "Foraminal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "discogenic_thoracic", "label": "Discogenic pain", "modifiers": ["global.confirm_status", "global.disc_details"] }, { "issue_key": "dish", "label": "DISH", "modifiers": ["global.confirm_status"] }, { "issue_key": "scheuermann", "label": "Scheuermann's disease", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolisthesis_thoracic", "label": "Spondylolisthesis", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolysis_thoracic", "label": "Spondylolysis", "modifiers": ["global.confirm_status"] }, { "issue_key": "fracture_thoracic", "label": "Fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "costovertebral_joint_pain", "label": "Costovertebral/costotransverse joint pain", "modifiers": ["global.confirm_status"] }, { "issue_key": "rib_fracture_stress", "label": "Rib fracture/stress fracture", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "cervical_spine", "label": "Cervical spine", "default_sides": ["midline", "left", "right", "bilateral"], "groups": [{ "group_key": "spine", "label": "Spine diagnoses", "items": [{ "issue_key": "facet_arthropathy_cervical", "label": "Facet joint syndrome/arthropathy", "modifiers": ["global.confirm_status"] }, { "issue_key": "cervical_radiculopathy", "label": "Cervical radiculopathy", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "cervical_myelopathy", "label": "Cervical myelopathy", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "central_canal_stenosis_cervical", "label": "Central canal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "foraminal_stenosis_cervical", "label": "Foraminal stenosis", "modifiers": ["global.confirm_status", "global.spine_level"] }, { "issue_key": "discogenic_cervical", "label": "Discogenic pain", "modifiers": ["global.confirm_status", "global.disc_details"] }, { "issue_key": "dish_cervical", "label": "DISH", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolisthesis_cervical", "label": "Spondylolisthesis", "modifiers": ["global.confirm_status"] }, { "issue_key": "spondylolysis_cervical", "label": "Spondylolysis", "modifiers": ["global.confirm_status"] }, { "issue_key": "fracture_cervical", "label": "Fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "whiplash", "label": "Whiplash-associated disorder", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "shoulder", "label": "Shoulder", "default_sides": ["left", "right"], "groups": [{ "group_key": "instability_acj", "label": "Instability / ACJ", "items": [{ "issue_key": "shoulder_dislocation", "label": "Subluxation/dislocation", "modifiers": ["global.confirm_status"] }, { "issue_key": "bankart_lesion", "label": "Bankart lesion", "modifiers": ["global.confirm_status"] }, { "issue_key": "hill_sachs", "label": "Hill-Sachs lesion", "modifiers": ["global.confirm_status"] }, { "issue_key": "acj_sprain", "label": "ACJ sprain", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "acj_dislocation", "label": "ACJ dislocation", "modifiers": ["global.confirm_status"] }] }, { "group_key": "rotator_cuff_biceps_labrum", "label": "Rotator cuff / Biceps / Labrum", "items": [{ "issue_key": "supraspinatus_issue", "label": "Supraspinatus (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "infraspinatus_issue", "label": "Infraspinatus (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "subscapularis_issue", "label": "Subscapularis (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "calcific_tendinopathy", "label": "Calcific tendinopathy", "modifiers": ["global.confirm_status"] }, { "issue_key": "lhb_issue", "label": "Long head of biceps (tenosynovitis/tendinopathy/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "slap_tear", "label": "SLAP tear", "modifiers": ["global.confirm_status"] }] }, { "group_key": "bursa_impingement_other", "label": "Bursa / Impingement / Other", "items": [{ "issue_key": "subacromial_bursitis", "label": "Subacromial bursitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "subacromial_pain", "label": "Subacromial pain syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "subacromial_impingement", "label": "Subacromial impingement", "modifiers": ["global.confirm_status"] }, { "issue_key": "gh_oa", "label": "Glenohumeral osteoarthritis", "modifiers": ["global.confirm_status"] }, { "issue_key": "adhesive_capsulitis", "label": "Adhesive capsulitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "scapular_dyskinesis", "label": "Scapular dyskinesis", "modifiers": ["global.confirm_status"] }, { "issue_key": "altered_shoulder_mechanics", "label": "Altered shoulder mechanics", "modifiers": ["global.confirm_status"] }, { "issue_key": "lat_dorsi_tear", "label": "Latissimus dorsi tear", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }] },
    { "region_key": "elbow", "label": "Elbow", "default_sides": ["left", "right"], "groups": [{ "group_key": "tendon_ligament", "label": "Tendon / Ligament", "items": [{ "issue_key": "lateral_epicondylalgia", "label": "Lateral epicondylalgia (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "medial_epicondylalgia", "label": "Medial epicondylalgia (tendinopathy/tear)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "distal_biceps_issue", "label": "Distal biceps (tendinopathy/tear/rupture)", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "triceps_issue", "label": "Triceps tendinopathy/tear", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "ucl_injury", "label": "UCL injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "lcl_injury_elbow", "label": "Lateral collateral ligament injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "nerve_joint_bone", "label": "Nerve / Joint / Bone", "items": [{ "issue_key": "pronator_syndrome", "label": "Pronator syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "cubital_tunnel", "label": "Ulnar nerve compression (cubital tunnel)", "modifiers": ["global.confirm_status"] }, { "issue_key": "elbow_effusion", "label": "Intra-articular effusion/synovitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "elbow_fracture", "label": "Fracture", "modifiers": ["global.confirm_status"] }, { "issue_key": "elbow_oa", "label": "Osteoarthritis", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "forearm", "label": "Forearm", "default_sides": ["left", "right"], "groups": [{ "group_key": "muscle_nerve_other", "label": "Muscle / Nerve / Other", "items": [{ "issue_key": "flexor_pronator_strain", "label": "Flexor-pronator mass strain", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "extensor_mass_strain", "label": "Extensor mass strain", "modifiers": ["global.confirm_status", "global.muscle_grading"] }, { "issue_key": "radial_tunnel", "label": "Radial tunnel syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "forearm_compartment_syndrome", "label": "Forearm compartment syndrome", "modifiers": ["global.confirm_status"] }] }] },
    { "region_key": "wrist_hand", "label": "Wrist & Hand", "default_sides": ["left", "right"], "groups": [{ "group_key": "tendon_tenosynovitis", "label": "Tendon / Tenosynovitis", "items": [{ "issue_key": "de_quervains", "label": "De Quervain's tenosynovitis", "modifiers": ["global.confirm_status"] }, { "issue_key": "ecu_issue", "label": "ECU tendinopathy/subluxation", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "trigger_finger_thumb", "label": "Trigger finger/thumb", "modifiers": ["global.confirm_status"] }] }, { "group_key": "nerve", "label": "Nerve", "items": [{ "issue_key": "carpal_tunnel", "label": "Carpal tunnel syndrome", "modifiers": ["global.confirm_status"] }, { "issue_key": "guyons_canal", "label": "Ulnar nerve (Guyon's canal)", "modifiers": ["global.confirm_status"] }] }, { "group_key": "ligament_complex", "label": "Ligament / Complex", "items": [{ "issue_key": "tfcc_tear", "label": "TFCC injury/tear", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "scapholunate_injury", "label": "Scapholunate ligament injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }, { "issue_key": "lunotriquetral_injury", "label": "Lunotriquetral ligament injury", "modifiers": ["global.confirm_status", "global.severity_generic"] }] }, { "group_key": "joint_other", "label": "Joint / Other", "items": [{ "issue_key": "thumb_cmc_oa", "label": "Thumb CMC osteoarthritis", "modifiers": ["global.confirm_status"] }, { "issue_key": "wrist_oa", "label": "Wrist osteoarthritis", "modifiers": ["global.confirm_status"] }, { "issue_key": "dupuytrens", "label": "Dupuytren's", "modifiers": ["global.confirm_status"] }, { "issue_key": "ganglion_cyst", "label": "Ganglion cyst", "modifiers": ["global.confirm_status"] }] }] }
  ]
};

export function getInjuryLibrary() {
  return injuryDiagnosisLibraryV1_1;
}

export function getRegionByKey(regionKey) {
  return injuryDiagnosisLibraryV1_1.regions.find(r => r.region_key === regionKey);
}

export function getIssueLabel(regionKey, groupKey, issueKey) {
  const region = getRegionByKey(regionKey);
  if (!region) return null;
  const group = region.groups.find(g => g.group_key === groupKey);
  if (!group) return null;
  const item = group.items.find(i => i.issue_key === issueKey);
  return item?.label || null;
}